#!/bin/bash

set -e

SCRIPT_DIR="$(cd `dirname $0` && pwd)"

cmd="$SCRIPT_DIR/tap-$1.sh"

if [[ -x ${cmd} ]]
then
    "$cmd" "${@:2}"
else
    echo 'Unknown command'
    echo ''
    "$SCRIPT_DIR/tap-help.sh"
    exit 1
fi
